/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Achievement {
  'id' : bigint,
  'title' : string,
  'year' : bigint,
  'description' : string,
  'category' : string,
}
export interface AdmissionInfo {
  'contact' : string,
  'fees' : string,
  'processSteps' : string,
  'requirements' : string,
}
export interface Content {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'date' : Time,
  'published' : boolean,
  'author' : string,
}
export interface Event {
  'id' : bigint,
  'title' : string,
  'date' : Time,
  'published' : boolean,
  'description' : string,
  'location' : string,
}
export type ExternalBlob = Uint8Array;
export interface FAQ {
  'id' : bigint,
  'question' : string,
  'order' : bigint,
  'published' : boolean,
  'answer' : string,
}
export interface GalleryImage {
  'id' : bigint,
  'title' : string,
  'date' : Time,
  'imageUrl' : string,
  'category' : string,
}
export interface GalleryItem {
  'id' : bigint,
  'title' : string,
  'blob' : ExternalBlob,
  'date' : Time,
  'category' : string,
}
export interface SiteInfo {
  'about' : string,
  'principalMessage' : string,
  'tagline' : string,
  'email' : string,
  'address' : string,
  'principalName' : string,
  'phone' : string,
  'schoolName' : string,
}
export interface Staff {
  'id' : bigint,
  'bio' : string,
  'order' : bigint,
  'name' : string,
  'role' : string,
  'photoUrl' : [] | [string],
  'department' : string,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addGalleryItem' : ActorMethod<[string, string, ExternalBlob], GalleryItem>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / ********* Achievements *************
   */
  'createAchievement' : ActorMethod<[Achievement], Achievement>,
  /**
   * / ********* Events *************
   */
  'createEvent' : ActorMethod<[Event], Event>,
  /**
   * / ********* FAQs *************
   */
  'createFAQ' : ActorMethod<[FAQ], FAQ>,
  /**
   * / ********* Gallery *************
   */
  'createGalleryImage' : ActorMethod<[GalleryImage], GalleryImage>,
  /**
   * / ********* News *************
   */
  'createNews' : ActorMethod<[Content], Content>,
  /**
   * / ********* Staff *************
   */
  'createStaff' : ActorMethod<[Staff], Staff>,
  'deleteAchievement' : ActorMethod<[bigint], undefined>,
  'deleteEvent' : ActorMethod<[bigint], undefined>,
  'deleteFAQ' : ActorMethod<[bigint], undefined>,
  'deleteGalleryImage' : ActorMethod<[bigint], undefined>,
  'deleteNews' : ActorMethod<[bigint], undefined>,
  'deleteStaff' : ActorMethod<[bigint], undefined>,
  'getAdmissionInfo' : ActorMethod<[], [] | [AdmissionInfo]>,
  'getAllAchievements' : ActorMethod<[], Array<Achievement>>,
  'getAllEvents' : ActorMethod<[], Array<Event>>,
  'getAllFAQs' : ActorMethod<[], Array<FAQ>>,
  'getAllGalleryImages' : ActorMethod<[], Array<GalleryImage>>,
  'getAllGalleryItems' : ActorMethod<[], Array<GalleryItem>>,
  'getAllNewsAdmin' : ActorMethod<[], Array<Content>>,
  'getAllStaff' : ActorMethod<[], Array<Staff>>,
  /**
   * / ********* User Profile *************
   */
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEvent' : ActorMethod<[bigint], Event>,
  'getNews' : ActorMethod<[bigint], Content>,
  'getPublishedEvents' : ActorMethod<[], Array<Event>>,
  'getPublishedFAQs' : ActorMethod<[], Array<FAQ>>,
  'getPublishedNews' : ActorMethod<[], Array<Content>>,
  'getSiteInfo' : ActorMethod<[], [] | [SiteInfo]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  /**
   * / ********* Admissions *************
   */
  'setAdmissionInfo' : ActorMethod<[AdmissionInfo], undefined>,
  /**
   * / ********* Site Info *************
   */
  'setSiteInfo' : ActorMethod<[SiteInfo], undefined>,
  'updateAchievement' : ActorMethod<[bigint, Achievement], undefined>,
  'updateEvent' : ActorMethod<[bigint, Event], undefined>,
  'updateFAQ' : ActorMethod<[bigint, FAQ], undefined>,
  'updateGalleryImage' : ActorMethod<[bigint, GalleryImage], undefined>,
  'updateNews' : ActorMethod<[bigint, Content], undefined>,
  'updateStaff' : ActorMethod<[bigint, Staff], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];