/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Time = IDL.Int;
export const GalleryItem = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'blob' : ExternalBlob,
  'date' : Time,
  'category' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Achievement = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'year' : IDL.Nat,
  'description' : IDL.Text,
  'category' : IDL.Text,
});
export const Event = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'date' : Time,
  'published' : IDL.Bool,
  'description' : IDL.Text,
  'location' : IDL.Text,
});
export const FAQ = IDL.Record({
  'id' : IDL.Nat,
  'question' : IDL.Text,
  'order' : IDL.Nat,
  'published' : IDL.Bool,
  'answer' : IDL.Text,
});
export const GalleryImage = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'date' : Time,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
});
export const Content = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'date' : Time,
  'published' : IDL.Bool,
  'author' : IDL.Text,
});
export const Staff = IDL.Record({
  'id' : IDL.Nat,
  'bio' : IDL.Text,
  'order' : IDL.Nat,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'photoUrl' : IDL.Opt(IDL.Text),
  'department' : IDL.Text,
});
export const AdmissionInfo = IDL.Record({
  'contact' : IDL.Text,
  'fees' : IDL.Text,
  'processSteps' : IDL.Text,
  'requirements' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const SiteInfo = IDL.Record({
  'about' : IDL.Text,
  'principalMessage' : IDL.Text,
  'tagline' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'principalName' : IDL.Text,
  'phone' : IDL.Text,
  'schoolName' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addGalleryItem' : IDL.Func(
      [IDL.Text, IDL.Text, ExternalBlob],
      [GalleryItem],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAchievement' : IDL.Func([Achievement], [Achievement], []),
  'createEvent' : IDL.Func([Event], [Event], []),
  'createFAQ' : IDL.Func([FAQ], [FAQ], []),
  'createGalleryImage' : IDL.Func([GalleryImage], [GalleryImage], []),
  'createNews' : IDL.Func([Content], [Content], []),
  'createStaff' : IDL.Func([Staff], [Staff], []),
  'deleteAchievement' : IDL.Func([IDL.Nat], [], []),
  'deleteEvent' : IDL.Func([IDL.Nat], [], []),
  'deleteFAQ' : IDL.Func([IDL.Nat], [], []),
  'deleteGalleryImage' : IDL.Func([IDL.Nat], [], []),
  'deleteNews' : IDL.Func([IDL.Nat], [], []),
  'deleteStaff' : IDL.Func([IDL.Nat], [], []),
  'getAdmissionInfo' : IDL.Func([], [IDL.Opt(AdmissionInfo)], ['query']),
  'getAllAchievements' : IDL.Func([], [IDL.Vec(Achievement)], ['query']),
  'getAllEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getAllFAQs' : IDL.Func([], [IDL.Vec(FAQ)], ['query']),
  'getAllGalleryImages' : IDL.Func([], [IDL.Vec(GalleryImage)], ['query']),
  'getAllGalleryItems' : IDL.Func([], [IDL.Vec(GalleryItem)], ['query']),
  'getAllNewsAdmin' : IDL.Func([], [IDL.Vec(Content)], ['query']),
  'getAllStaff' : IDL.Func([], [IDL.Vec(Staff)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEvent' : IDL.Func([IDL.Nat], [Event], ['query']),
  'getNews' : IDL.Func([IDL.Nat], [Content], ['query']),
  'getPublishedEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getPublishedFAQs' : IDL.Func([], [IDL.Vec(FAQ)], ['query']),
  'getPublishedNews' : IDL.Func([], [IDL.Vec(Content)], ['query']),
  'getSiteInfo' : IDL.Func([], [IDL.Opt(SiteInfo)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setAdmissionInfo' : IDL.Func([AdmissionInfo], [], []),
  'setSiteInfo' : IDL.Func([SiteInfo], [], []),
  'updateAchievement' : IDL.Func([IDL.Nat, Achievement], [], []),
  'updateEvent' : IDL.Func([IDL.Nat, Event], [], []),
  'updateFAQ' : IDL.Func([IDL.Nat, FAQ], [], []),
  'updateGalleryImage' : IDL.Func([IDL.Nat, GalleryImage], [], []),
  'updateNews' : IDL.Func([IDL.Nat, Content], [], []),
  'updateStaff' : IDL.Func([IDL.Nat, Staff], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Time = IDL.Int;
  const GalleryItem = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'blob' : ExternalBlob,
    'date' : Time,
    'category' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Achievement = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'year' : IDL.Nat,
    'description' : IDL.Text,
    'category' : IDL.Text,
  });
  const Event = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'date' : Time,
    'published' : IDL.Bool,
    'description' : IDL.Text,
    'location' : IDL.Text,
  });
  const FAQ = IDL.Record({
    'id' : IDL.Nat,
    'question' : IDL.Text,
    'order' : IDL.Nat,
    'published' : IDL.Bool,
    'answer' : IDL.Text,
  });
  const GalleryImage = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'date' : Time,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
  });
  const Content = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'date' : Time,
    'published' : IDL.Bool,
    'author' : IDL.Text,
  });
  const Staff = IDL.Record({
    'id' : IDL.Nat,
    'bio' : IDL.Text,
    'order' : IDL.Nat,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'photoUrl' : IDL.Opt(IDL.Text),
    'department' : IDL.Text,
  });
  const AdmissionInfo = IDL.Record({
    'contact' : IDL.Text,
    'fees' : IDL.Text,
    'processSteps' : IDL.Text,
    'requirements' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const SiteInfo = IDL.Record({
    'about' : IDL.Text,
    'principalMessage' : IDL.Text,
    'tagline' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'principalName' : IDL.Text,
    'phone' : IDL.Text,
    'schoolName' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addGalleryItem' : IDL.Func(
        [IDL.Text, IDL.Text, ExternalBlob],
        [GalleryItem],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAchievement' : IDL.Func([Achievement], [Achievement], []),
    'createEvent' : IDL.Func([Event], [Event], []),
    'createFAQ' : IDL.Func([FAQ], [FAQ], []),
    'createGalleryImage' : IDL.Func([GalleryImage], [GalleryImage], []),
    'createNews' : IDL.Func([Content], [Content], []),
    'createStaff' : IDL.Func([Staff], [Staff], []),
    'deleteAchievement' : IDL.Func([IDL.Nat], [], []),
    'deleteEvent' : IDL.Func([IDL.Nat], [], []),
    'deleteFAQ' : IDL.Func([IDL.Nat], [], []),
    'deleteGalleryImage' : IDL.Func([IDL.Nat], [], []),
    'deleteNews' : IDL.Func([IDL.Nat], [], []),
    'deleteStaff' : IDL.Func([IDL.Nat], [], []),
    'getAdmissionInfo' : IDL.Func([], [IDL.Opt(AdmissionInfo)], ['query']),
    'getAllAchievements' : IDL.Func([], [IDL.Vec(Achievement)], ['query']),
    'getAllEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getAllFAQs' : IDL.Func([], [IDL.Vec(FAQ)], ['query']),
    'getAllGalleryImages' : IDL.Func([], [IDL.Vec(GalleryImage)], ['query']),
    'getAllGalleryItems' : IDL.Func([], [IDL.Vec(GalleryItem)], ['query']),
    'getAllNewsAdmin' : IDL.Func([], [IDL.Vec(Content)], ['query']),
    'getAllStaff' : IDL.Func([], [IDL.Vec(Staff)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEvent' : IDL.Func([IDL.Nat], [Event], ['query']),
    'getNews' : IDL.Func([IDL.Nat], [Content], ['query']),
    'getPublishedEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getPublishedFAQs' : IDL.Func([], [IDL.Vec(FAQ)], ['query']),
    'getPublishedNews' : IDL.Func([], [IDL.Vec(Content)], ['query']),
    'getSiteInfo' : IDL.Func([], [IDL.Opt(SiteInfo)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setAdmissionInfo' : IDL.Func([AdmissionInfo], [], []),
    'setSiteInfo' : IDL.Func([SiteInfo], [], []),
    'updateAchievement' : IDL.Func([IDL.Nat, Achievement], [], []),
    'updateEvent' : IDL.Func([IDL.Nat, Event], [], []),
    'updateFAQ' : IDL.Func([IDL.Nat, FAQ], [], []),
    'updateGalleryImage' : IDL.Func([IDL.Nat, GalleryImage], [], []),
    'updateNews' : IDL.Func([IDL.Nat, Content], [], []),
    'updateStaff' : IDL.Func([IDL.Nat, Staff], [], []),
  });
};

export const init = ({ IDL }) => { return []; };