/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface FAQ {
    id: bigint;
    question: string;
    order: bigint;
    published: boolean;
    answer: string;
}
export interface AdmissionInfo {
    contact: string;
    fees: string;
    processSteps: string;
    requirements: string;
}
export type Time = bigint;
export interface Content {
    id: bigint;
    title: string;
    content: string;
    date: Time;
    published: boolean;
    author: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Event {
    id: bigint;
    title: string;
    date: Time;
    published: boolean;
    description: string;
    location: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Achievement {
    id: bigint;
    title: string;
    year: bigint;
    description: string;
    category: string;
}
export interface GalleryImage {
    id: bigint;
    title: string;
    date: Time;
    imageUrl: string;
    category: string;
}
export interface Staff {
    id: bigint;
    bio: string;
    order: bigint;
    name: string;
    role: string;
    photoUrl?: string;
    department: string;
}
export interface GalleryItem {
    id: bigint;
    title: string;
    blob: ExternalBlob;
    date: Time;
    category: string;
}
export interface SiteInfo {
    about: string;
    principalMessage: string;
    tagline: string;
    email: string;
    address: string;
    principalName: string;
    phone: string;
    schoolName: string;
}
export interface UserProfile {
    name: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addGalleryItem(title: string, category: string, blob: ExternalBlob): Promise<GalleryItem>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    /**
     * / ********* Achievements *************
     */
    createAchievement(achievementInput: Achievement): Promise<Achievement>;
    /**
     * / ********* Events *************
     */
    createEvent(eventInput: Event): Promise<Event>;
    /**
     * / ********* FAQs *************
     */
    createFAQ(faqInput: FAQ): Promise<FAQ>;
    /**
     * / ********* Gallery *************
     */
    createGalleryImage(imageInput: GalleryImage): Promise<GalleryImage>;
    /**
     * / ********* News *************
     */
    createNews(newsInput: Content): Promise<Content>;
    /**
     * / ********* Staff *************
     */
    createStaff(staffInput: Staff): Promise<Staff>;
    deleteAchievement(id: bigint): Promise<void>;
    deleteEvent(id: bigint): Promise<void>;
    deleteFAQ(id: bigint): Promise<void>;
    deleteGalleryImage(id: bigint): Promise<void>;
    deleteNews(id: bigint): Promise<void>;
    deleteStaff(id: bigint): Promise<void>;
    getAdmissionInfo(): Promise<AdmissionInfo | null>;
    getAllAchievements(): Promise<Array<Achievement>>;
    getAllEvents(): Promise<Array<Event>>;
    getAllFAQs(): Promise<Array<FAQ>>;
    getAllGalleryImages(): Promise<Array<GalleryImage>>;
    getAllGalleryItems(): Promise<Array<GalleryItem>>;
    getAllNewsAdmin(): Promise<Array<Content>>;
    getAllStaff(): Promise<Array<Staff>>;
    /**
     * / ********* User Profile *************
     */
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getEvent(id: bigint): Promise<Event>;
    getNews(id: bigint): Promise<Content>;
    getPublishedEvents(): Promise<Array<Event>>;
    getPublishedFAQs(): Promise<Array<FAQ>>;
    getPublishedNews(): Promise<Array<Content>>;
    getSiteInfo(): Promise<SiteInfo | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    /**
     * / ********* Admissions *************
     */
    setAdmissionInfo(info: AdmissionInfo): Promise<void>;
    /**
     * / ********* Site Info *************
     */
    setSiteInfo(info: SiteInfo): Promise<void>;
    updateAchievement(id: bigint, achievementInput: Achievement): Promise<void>;
    updateEvent(id: bigint, eventInput: Event): Promise<void>;
    updateFAQ(id: bigint, faqInput: FAQ): Promise<void>;
    updateGalleryImage(id: bigint, imageInput: GalleryImage): Promise<void>;
    updateNews(id: bigint, newsInput: Content): Promise<void>;
    updateStaff(id: bigint, staffInput: Staff): Promise<void>;
}
import type { AdmissionInfo as _AdmissionInfo, ExternalBlob as _ExternalBlob, GalleryItem as _GalleryItem, SiteInfo as _SiteInfo, Staff as _Staff, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addGalleryItem(arg0: string, arg1: string, arg2: ExternalBlob): Promise<GalleryItem> {
        if (this.processError) {
            try {
                const result = await this.actor.addGalleryItem(arg0, arg1, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg2));
                return from_candid_GalleryItem_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGalleryItem(arg0, arg1, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg2));
            return from_candid_GalleryItem_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createAchievement(arg0: Achievement): Promise<Achievement> {
        if (this.processError) {
            try {
                const result = await this.actor.createAchievement(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAchievement(arg0);
            return result;
        }
    }
    async createEvent(arg0: Event): Promise<Event> {
        if (this.processError) {
            try {
                const result = await this.actor.createEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEvent(arg0);
            return result;
        }
    }
    async createFAQ(arg0: FAQ): Promise<FAQ> {
        if (this.processError) {
            try {
                const result = await this.actor.createFAQ(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createFAQ(arg0);
            return result;
        }
    }
    async createGalleryImage(arg0: GalleryImage): Promise<GalleryImage> {
        if (this.processError) {
            try {
                const result = await this.actor.createGalleryImage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createGalleryImage(arg0);
            return result;
        }
    }
    async createNews(arg0: Content): Promise<Content> {
        if (this.processError) {
            try {
                const result = await this.actor.createNews(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createNews(arg0);
            return result;
        }
    }
    async createStaff(arg0: Staff): Promise<Staff> {
        if (this.processError) {
            try {
                const result = await this.actor.createStaff(to_candid_Staff_n14(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Staff_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createStaff(to_candid_Staff_n14(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Staff_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteAchievement(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAchievement(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAchievement(arg0);
            return result;
        }
    }
    async deleteEvent(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEvent(arg0);
            return result;
        }
    }
    async deleteFAQ(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFAQ(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFAQ(arg0);
            return result;
        }
    }
    async deleteGalleryImage(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGalleryImage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGalleryImage(arg0);
            return result;
        }
    }
    async deleteNews(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteNews(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteNews(arg0);
            return result;
        }
    }
    async deleteStaff(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStaff(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStaff(arg0);
            return result;
        }
    }
    async getAdmissionInfo(): Promise<AdmissionInfo | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdmissionInfo();
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdmissionInfo();
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllAchievements(): Promise<Array<Achievement>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAchievements();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAchievements();
            return result;
        }
    }
    async getAllEvents(): Promise<Array<Event>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEvents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEvents();
            return result;
        }
    }
    async getAllFAQs(): Promise<Array<FAQ>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFAQs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFAQs();
            return result;
        }
    }
    async getAllGalleryImages(): Promise<Array<GalleryImage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllGalleryImages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllGalleryImages();
            return result;
        }
    }
    async getAllGalleryItems(): Promise<Array<GalleryItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllGalleryItems();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllGalleryItems();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllNewsAdmin(): Promise<Array<Content>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllNewsAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllNewsAdmin();
            return result;
        }
    }
    async getAllStaff(): Promise<Array<Staff>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStaff();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStaff();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEvent(arg0: bigint): Promise<Event> {
        if (this.processError) {
            try {
                const result = await this.actor.getEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEvent(arg0);
            return result;
        }
    }
    async getNews(arg0: bigint): Promise<Content> {
        if (this.processError) {
            try {
                const result = await this.actor.getNews(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNews(arg0);
            return result;
        }
    }
    async getPublishedEvents(): Promise<Array<Event>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublishedEvents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublishedEvents();
            return result;
        }
    }
    async getPublishedFAQs(): Promise<Array<FAQ>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublishedFAQs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublishedFAQs();
            return result;
        }
    }
    async getPublishedNews(): Promise<Array<Content>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublishedNews();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublishedNews();
            return result;
        }
    }
    async getSiteInfo(): Promise<SiteInfo | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSiteInfo();
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSiteInfo();
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setAdmissionInfo(arg0: AdmissionInfo): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setAdmissionInfo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAdmissionInfo(arg0);
            return result;
        }
    }
    async setSiteInfo(arg0: SiteInfo): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setSiteInfo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setSiteInfo(arg0);
            return result;
        }
    }
    async updateAchievement(arg0: bigint, arg1: Achievement): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAchievement(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAchievement(arg0, arg1);
            return result;
        }
    }
    async updateEvent(arg0: bigint, arg1: Event): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEvent(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEvent(arg0, arg1);
            return result;
        }
    }
    async updateFAQ(arg0: bigint, arg1: FAQ): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFAQ(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFAQ(arg0, arg1);
            return result;
        }
    }
    async updateGalleryImage(arg0: bigint, arg1: GalleryImage): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGalleryImage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGalleryImage(arg0, arg1);
            return result;
        }
    }
    async updateNews(arg0: bigint, arg1: Content): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateNews(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateNews(arg0, arg1);
            return result;
        }
    }
    async updateStaff(arg0: bigint, arg1: Staff): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStaff(arg0, to_candid_Staff_n14(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStaff(arg0, to_candid_Staff_n14(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
async function from_candid_ExternalBlob_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_GalleryItem_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GalleryItem): Promise<GalleryItem> {
    return await from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Staff_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Staff): Staff {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AdmissionInfo]): AdmissionInfo | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SiteInfo]): SiteInfo | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    blob: _ExternalBlob;
    date: _Time;
    category: string;
}): Promise<{
    id: bigint;
    title: string;
    blob: ExternalBlob;
    date: Time;
    category: string;
}> {
    return {
        id: value.id,
        title: value.title,
        blob: await from_candid_ExternalBlob_n11(_uploadFile, _downloadFile, value.blob),
        date: value.date,
        category: value.category
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    bio: string;
    order: bigint;
    name: string;
    role: string;
    photoUrl: [] | [string];
    department: string;
}): {
    id: bigint;
    bio: string;
    order: bigint;
    name: string;
    role: string;
    photoUrl?: string;
    department: string;
} {
    return {
        id: value.id,
        bio: value.bio,
        order: value.order,
        name: value.name,
        role: value.role,
        photoUrl: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.photoUrl)),
        department: value.department
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GalleryItem>): Promise<Array<GalleryItem>> {
    return await Promise.all(value.map(async (x)=>await from_candid_GalleryItem_n9(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Staff>): Array<Staff> {
    return value.map((x)=>from_candid_Staff_n16(_uploadFile, _downloadFile, x));
}
async function to_candid_ExternalBlob_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_Staff_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Staff): _Staff {
    return to_candid_record_n15(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    bio: string;
    order: bigint;
    name: string;
    role: string;
    photoUrl?: string;
    department: string;
}): {
    id: bigint;
    bio: string;
    order: bigint;
    name: string;
    role: string;
    photoUrl: [] | [string];
    department: string;
} {
    return {
        id: value.id,
        bio: value.bio,
        order: value.order,
        name: value.name,
        role: value.role,
        photoUrl: value.photoUrl ? candid_some(value.photoUrl) : candid_none(),
        department: value.department
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
